# Generated by Django 2.1.3 on 2020-02-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='content',
            field=models.TextField(default='', verbose_name='关于内容'),
        ),
    ]
