# Generated by Django 2.1.3 on 2020-02-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_about_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='count',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='count',
        ),
    ]
